name: pytest
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv==2023.10.20
        pip install codecov==2.1.13 \
                    pytest==7.4.3 \
                    pytest-cov==4.1.0 \
                    pytest-metadata==3.0.0 \
                    pytest-mock==3.12.0 \
                    pytest-subtests==0.11.0 \
                    six==1.16.0
        pip install --no-index --no-deps resources/home/dnanexus/packages/*
        pipenv install --dev
    - name: Build bcftools
      run: |
        wget https://github.com/samtools/bcftools/releases/download/1.18/bcftools-1.18.tar.bz2
        tar xf bcftools-1.18.tar.bz2
        cd bcftools-1.18
        ./configure --prefix=/usr/local/ --disable-bz2 --disable-lzma
        sudo make
        sudo make install
    - name: Build htslib
      run: |
        wget https://github.com/samtools/htslib/releases/download/1.18/htslib-1.18.tar.bz2
        tar xf htslib-1.18.tar.bz2
        cd htslib-1.18
        ./configure --prefix=/usr/local/ --disable-bz2 --disable-lzma
        sudo make
        sudo make install
    - name: Test with pytest
      run: |
        pytest -v --cov resources/home/dnanexus/generate_gcnv_bed/tests/unit/

