name: pytest
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv codecov
        python3 -m pip install --no-index --no-deps resources/home/dnanexus/packages/*
        pipenv install --dev
    - name: Test with pytest
      run: |
        pytest -v --cov --count 10 --random-order resources/home/dnanexus/generate_gcnv_bed/tests/unit/
